import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NpProgress from "@/components/NpProgress";
import ReactQueryProvider from "@/providers/ReactQuery";
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ReactQueryProvider>
            {children}
            <NpProgress />
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
